### ISSUE TITLE
waiting for nameserver for ever

### ISSUE THREAD

**Issue by eyadsibai** [amplab/docker-scripts#28]
getting this msg and it runs for ever...

```
sudo ./deploy/deploy.sh -i amplab/spark:0.9.0 
*** Starting Spark 0.9.0 ***
starting nameserver container
WARNING: WARNING: Local (127.0.0.1) DNS resolver found in resolv.conf and containers can't use it. Using default external servers : [8.8.8.8 8.8.4.4]
started nameserver container:  4a6ba6682fc59b1ea99fc82644c16fd8c6b5aeffa158b3143076e74422640564
DNS host->IP file mapped:      /tmp/dnsdir_17059/0hosts
NAMESERVER_IP:                 172.17.0.5
waiting for nameserver to come up ............
```

**Comment by cestella** [comment]
I'm in the same spot.  If you do a sudo docker logs 4a, you'll see the culprit is the following error: "dnsmasq: setting capabilities failed: Operation not permitted"

If you look at the dnsmaq faq at http://www.thekelleys.org.uk/dnsmasq/docs/FAQ:
Q: Dnsmasq fails to start up with a message about capabilities.
   Why did that happen and what can do to fix it?

A: Change your kernel configuration: either deselect CONFIG_SECURITY
   _or_ select CONFIG_SECURITY_CAPABILITIES. Alternatively, you can 
   remove the need to set capabilities by running dnsmasq as root.

I'm guessing that this needs to be changed in the host OS.  I'm working through it now, so I'll update you when/if I figure it out.

**Comment by henrikno** [comment]
There's a workaround described here: https://github.com/dotcloud/docker/issues/1951

**Comment by cestella** [comment]
This workaround worked for me.

**Comment by AndreSchumacher** [comment]
Could you try again pulling the nameserver image (amplab/dnsmasq-precise)? I just merged a pill request (PR #29) that should fix this issue. I tested with Docker version 0.8.1. No other workarounds should be necessary.

**Comment by eyadsibai** [comment]
This resolved the issue +1
but I have now same problem as in issue #27

**Comment by AndreSchumacher** [comment]
OK, thanks. #27 seems to be a separate issue so I'm closing this one here now.
